/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReportType = IDL.Variant({
  'pl' : IDL.Null,
  'gst' : IDL.Null,
  'balance_sheet' : IDL.Null,
  'cash_flow' : IDL.Null,
  'data_analysis' : IDL.Null,
});
export const Time = IDL.Int;
export const DatasetSession = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'analysisResults' : IDL.Text,
  'rawData' : IDL.Text,
});
export const ReportSession = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'formData' : IDL.Text,
  'results' : IDL.Text,
  'reportType' : ReportType,
  'updatedAt' : Time,
});
export const DashboardStats = IDL.Record({
  'dataAnalysisCount' : IDL.Nat,
  'cashFlowCount' : IDL.Nat,
  'plCount' : IDL.Nat,
  'balanceSheetCount' : IDL.Nat,
  'gstCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createDatasetSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createReportSession' : IDL.Func(
      [IDL.Text, IDL.Text, ReportType, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteDatasetSession' : IDL.Func([IDL.Text], [], []),
  'deleteReportSession' : IDL.Func([IDL.Text], [], []),
  'getAllDatasetSessions' : IDL.Func([], [IDL.Vec(DatasetSession)], ['query']),
  'getAllReportSessions' : IDL.Func([], [IDL.Vec(ReportSession)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDatasetSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DatasetSession)],
      ['query'],
    ),
  'getReportSession' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ReportSession)],
      ['query'],
    ),
  'updateDatasetSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateReportSession' : IDL.Func(
      [IDL.Text, IDL.Text, ReportType, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReportType = IDL.Variant({
    'pl' : IDL.Null,
    'gst' : IDL.Null,
    'balance_sheet' : IDL.Null,
    'cash_flow' : IDL.Null,
    'data_analysis' : IDL.Null,
  });
  const Time = IDL.Int;
  const DatasetSession = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'analysisResults' : IDL.Text,
    'rawData' : IDL.Text,
  });
  const ReportSession = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'formData' : IDL.Text,
    'results' : IDL.Text,
    'reportType' : ReportType,
    'updatedAt' : Time,
  });
  const DashboardStats = IDL.Record({
    'dataAnalysisCount' : IDL.Nat,
    'cashFlowCount' : IDL.Nat,
    'plCount' : IDL.Nat,
    'balanceSheetCount' : IDL.Nat,
    'gstCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createDatasetSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createReportSession' : IDL.Func(
        [IDL.Text, IDL.Text, ReportType, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteDatasetSession' : IDL.Func([IDL.Text], [], []),
    'deleteReportSession' : IDL.Func([IDL.Text], [], []),
    'getAllDatasetSessions' : IDL.Func(
        [],
        [IDL.Vec(DatasetSession)],
        ['query'],
      ),
    'getAllReportSessions' : IDL.Func([], [IDL.Vec(ReportSession)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDatasetSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DatasetSession)],
        ['query'],
      ),
    'getReportSession' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReportSession)],
        ['query'],
      ),
    'updateDatasetSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateReportSession' : IDL.Func(
        [IDL.Text, IDL.Text, ReportType, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };