/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'dataAnalysisCount' : bigint,
  'cashFlowCount' : bigint,
  'plCount' : bigint,
  'balanceSheetCount' : bigint,
  'gstCount' : bigint,
}
export interface DatasetSession {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'analysisResults' : string,
  'rawData' : string,
}
export interface ReportSession {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'formData' : string,
  'results' : string,
  'reportType' : ReportType,
  'updatedAt' : Time,
}
export type ReportType = { 'pl' : null } |
  { 'gst' : null } |
  { 'balance_sheet' : null } |
  { 'cash_flow' : null } |
  { 'data_analysis' : null };
export type Time = bigint;
export interface _SERVICE {
  'createDatasetSession' : ActorMethod<
    [string, string, string, string],
    string
  >,
  'createReportSession' : ActorMethod<
    [string, string, ReportType, string, string],
    string
  >,
  'deleteDatasetSession' : ActorMethod<[string], undefined>,
  'deleteReportSession' : ActorMethod<[string], undefined>,
  'getAllDatasetSessions' : ActorMethod<[], Array<DatasetSession>>,
  'getAllReportSessions' : ActorMethod<[], Array<ReportSession>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDatasetSession' : ActorMethod<[string], [] | [DatasetSession]>,
  'getReportSession' : ActorMethod<[string], [] | [ReportSession]>,
  'updateDatasetSession' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateReportSession' : ActorMethod<
    [string, string, ReportType, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];