/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DatasetSession {
    id: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    updatedAt: Time;
    analysisResults: string;
    rawData: string;
}
export type Time = bigint;
export interface DashboardStats {
    dataAnalysisCount: bigint;
    cashFlowCount: bigint;
    plCount: bigint;
    balanceSheetCount: bigint;
    gstCount: bigint;
}
export interface ReportSession {
    id: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    formData: string;
    results: string;
    reportType: ReportType;
    updatedAt: Time;
}
export enum ReportType {
    pl = "pl",
    gst = "gst",
    balance_sheet = "balance_sheet",
    cash_flow = "cash_flow",
    data_analysis = "data_analysis"
}
export interface backendInterface {
    createDatasetSession(id: string, name: string, rawData: string, analysisResults: string): Promise<string>;
    createReportSession(id: string, name: string, reportType: ReportType, formData: string, results: string): Promise<string>;
    deleteDatasetSession(id: string): Promise<void>;
    deleteReportSession(id: string): Promise<void>;
    getAllDatasetSessions(): Promise<Array<DatasetSession>>;
    getAllReportSessions(): Promise<Array<ReportSession>>;
    getDashboardStats(): Promise<DashboardStats>;
    getDatasetSession(id: string): Promise<DatasetSession | null>;
    getReportSession(id: string): Promise<ReportSession | null>;
    updateDatasetSession(id: string, name: string, rawData: string, analysisResults: string): Promise<void>;
    updateReportSession(id: string, name: string, reportType: ReportType, formData: string, results: string): Promise<void>;
}
import type { DatasetSession as _DatasetSession, ReportSession as _ReportSession, ReportType as _ReportType, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createDatasetSession(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createDatasetSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDatasetSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createReportSession(arg0: string, arg1: string, arg2: ReportType, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createReportSession(arg0, arg1, to_candid_ReportType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReportSession(arg0, arg1, to_candid_ReportType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async deleteDatasetSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDatasetSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDatasetSession(arg0);
            return result;
        }
    }
    async deleteReportSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReportSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReportSession(arg0);
            return result;
        }
    }
    async getAllDatasetSessions(): Promise<Array<DatasetSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDatasetSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDatasetSessions();
            return result;
        }
    }
    async getAllReportSessions(): Promise<Array<ReportSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReportSessions();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReportSessions();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDatasetSession(arg0: string): Promise<DatasetSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDatasetSession(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDatasetSession(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportSession(arg0: string): Promise<ReportSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportSession(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportSession(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDatasetSession(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDatasetSession(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDatasetSession(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateReportSession(arg0: string, arg1: string, arg2: ReportType, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportSession(arg0, arg1, to_candid_ReportType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportSession(arg0, arg1, to_candid_ReportType_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
}
function from_candid_ReportSession_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportSession): ReportSession {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ReportType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportType): ReportType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DatasetSession]): DatasetSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReportSession]): ReportSession | null {
    return value.length === 0 ? null : from_candid_ReportSession_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    name: string;
    createdAt: _Time;
    formData: string;
    results: string;
    reportType: _ReportType;
    updatedAt: _Time;
}): {
    id: string;
    owner: Principal;
    name: string;
    createdAt: Time;
    formData: string;
    results: string;
    reportType: ReportType;
    updatedAt: Time;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        formData: value.formData,
        results: value.results,
        reportType: from_candid_ReportType_n6(_uploadFile, _downloadFile, value.reportType),
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pl: null;
} | {
    gst: null;
} | {
    balance_sheet: null;
} | {
    cash_flow: null;
} | {
    data_analysis: null;
}): ReportType {
    return "pl" in value ? ReportType.pl : "gst" in value ? ReportType.gst : "balance_sheet" in value ? ReportType.balance_sheet : "cash_flow" in value ? ReportType.cash_flow : "data_analysis" in value ? ReportType.data_analysis : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReportSession>): Array<ReportSession> {
    return value.map((x)=>from_candid_ReportSession_n4(_uploadFile, _downloadFile, x));
}
function to_candid_ReportType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): _ReportType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): {
    pl: null;
} | {
    gst: null;
} | {
    balance_sheet: null;
} | {
    cash_flow: null;
} | {
    data_analysis: null;
} {
    return value == ReportType.pl ? {
        pl: null
    } : value == ReportType.gst ? {
        gst: null
    } : value == ReportType.balance_sheet ? {
        balance_sheet: null
    } : value == ReportType.cash_flow ? {
        cash_flow: null
    } : value == ReportType.data_analysis ? {
        data_analysis: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
